# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['bumpath_backend_standalone_final.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('minimal-ltmao/src/LtMAO', 'LtMAO'),
        ('minimal-ltmao/src/LtMAO/pyRitoFile', 'pyRitoFile'),
        ('minimal-ltmao', 'minimal-ltmao'),
    ],
    hiddenimports=[
        # All pyRitoFile modules
        'pyRitoFile.bin',
        'pyRitoFile.wad', 
        'pyRitoFile.stream',
        'pyRitoFile.structs',
        'pyRitoFile.helper',
        'pyRitoFile.anm',
        'pyRitoFile.skl',
        'pyRitoFile.skn',
        'pyRitoFile.tex',
        'pyRitoFile.bnk',
        'pyRitoFile.mapgeo',
        'pyRitoFile.so',
        'pyRitoFile.wpk',
        # All LtMAO modules
        'LtMAO.bumpath',
        'LtMAO.hash_helper',
        'LtMAO.lepath',
        'LtMAO.wad_tool',
        'LtMAO.texsmart',
        'LtMAO.Ritoddstex',
        'LtMAO.ritobin',
        'LtMAO.sborf',
        'LtMAO.setting',
        'LtMAO.skin0',
        'LtMAO.tools',
        # LtMAO.pyRitoFile modules (nested imports)
        'LtMAO.pyRitoFile.bin',
        'LtMAO.pyRitoFile.wad',
        'LtMAO.pyRitoFile.stream',
        'LtMAO.pyRitoFile.structs',
        'LtMAO.pyRitoFile.helper',
        'LtMAO.pyRitoFile.anm',
        'LtMAO.pyRitoFile.skl',
        'LtMAO.pyRitoFile.skn',
        'LtMAO.pyRitoFile.tex',
        'LtMAO.pyRitoFile.bnk',
        'LtMAO.pyRitoFile.mapgeo',
        'LtMAO.pyRitoFile.so',
        'LtMAO.pyRitoFile.wpk',
        # Web framework
        'flask',
        'flask_cors',
        'requests'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='bumpath_backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
